// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/simple/enum.proto

package enumpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DayOfTheWeek int32

const (
	DayOfTheWeek_UNKNOWN DayOfTheWeek = 0
	DayOfTheWeek_MON     DayOfTheWeek = 1
	DayOfTheWeek_TUES    DayOfTheWeek = 2
	DayOfTheWeek_WED     DayOfTheWeek = 3
	DayOfTheWeek_THUR    DayOfTheWeek = 4
	DayOfTheWeek_FRI     DayOfTheWeek = 5
	DayOfTheWeek_SAT     DayOfTheWeek = 6
	DayOfTheWeek_SUN     DayOfTheWeek = 7
)

var DayOfTheWeek_name = map[int32]string{
	0: "UNKNOWN",
	1: "MON",
	2: "TUES",
	3: "WED",
	4: "THUR",
	5: "FRI",
	6: "SAT",
	7: "SUN",
}

var DayOfTheWeek_value = map[string]int32{
	"UNKNOWN": 0,
	"MON":     1,
	"TUES":    2,
	"WED":     3,
	"THUR":    4,
	"FRI":     5,
	"SAT":     6,
	"SUN":     7,
}

func (x DayOfTheWeek) String() string {
	return proto.EnumName(DayOfTheWeek_name, int32(x))
}

func (DayOfTheWeek) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8adf78d7da3b6003, []int{0}
}

type EnumMessage struct {
	Id                   int32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Day                  DayOfTheWeek `protobuf:"varint,2,opt,name=day,proto3,enum=example.enumerations.DayOfTheWeek" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EnumMessage) Reset()         { *m = EnumMessage{} }
func (m *EnumMessage) String() string { return proto.CompactTextString(m) }
func (*EnumMessage) ProtoMessage()    {}
func (*EnumMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8adf78d7da3b6003, []int{0}
}

func (m *EnumMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumMessage.Unmarshal(m, b)
}
func (m *EnumMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumMessage.Marshal(b, m, deterministic)
}
func (m *EnumMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumMessage.Merge(m, src)
}
func (m *EnumMessage) XXX_Size() int {
	return xxx_messageInfo_EnumMessage.Size(m)
}
func (m *EnumMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EnumMessage proto.InternalMessageInfo

func (m *EnumMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EnumMessage) GetDay() DayOfTheWeek {
	if m != nil {
		return m.Day
	}
	return DayOfTheWeek_UNKNOWN
}

func init() {
	proto.RegisterEnum("example.enumerations.DayOfTheWeek", DayOfTheWeek_name, DayOfTheWeek_value)
	proto.RegisterType((*EnumMessage)(nil), "example.enumerations.EnumMessage")
}

func init() { proto.RegisterFile("github.com/simple/enum.proto", fileDescriptor_8adf78d7da3b6003) }

var fileDescriptor_8adf78d7da3b6003 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x2f, 0xce, 0xcc, 0x2d, 0xc8, 0x49, 0xd5, 0x4f, 0xcd,
	0x2b, 0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x49, 0xad, 0x48, 0x04, 0x89, 0xe9,
	0x81, 0xc4, 0x52, 0x8b, 0x12, 0x4b, 0x32, 0xf3, 0xf3, 0x8a, 0x95, 0x82, 0xb9, 0xb8, 0x5d, 0xf3,
	0x4a, 0x73, 0x7d, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x98, 0x32, 0x53, 0x84, 0x4c, 0xb8, 0x98, 0x53, 0x12, 0x2b,
	0x25, 0x98, 0x14, 0x18, 0x35, 0xf8, 0x8c, 0x94, 0xf4, 0xb0, 0x19, 0xa1, 0xe7, 0x92, 0x58, 0xe9,
	0x9f, 0x16, 0x92, 0x91, 0x1a, 0x9e, 0x9a, 0x9a, 0x1d, 0x04, 0x52, 0xae, 0x15, 0xc3, 0xc5, 0x83,
	0x2c, 0x28, 0xc4, 0xcd, 0xc5, 0x1e, 0xea, 0xe7, 0xed, 0xe7, 0x1f, 0xee, 0x27, 0xc0, 0x20, 0xc4,
	0xce, 0xc5, 0xec, 0xeb, 0xef, 0x27, 0xc0, 0x28, 0xc4, 0xc1, 0xc5, 0x12, 0x12, 0xea, 0x1a, 0x2c,
	0xc0, 0x04, 0x12, 0x0a, 0x77, 0x75, 0x11, 0x60, 0x06, 0x0b, 0x79, 0x84, 0x06, 0x09, 0xb0, 0x80,
	0x84, 0xdc, 0x82, 0x3c, 0x05, 0x58, 0x41, 0x8c, 0x60, 0xc7, 0x10, 0x01, 0x36, 0x30, 0x23, 0xd4,
	0x4f, 0x80, 0xdd, 0x89, 0x23, 0x8a, 0x0d, 0x64, 0x7f, 0x41, 0x52, 0x12, 0x1b, 0xd8, 0x67, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0x79, 0x50, 0x2e, 0xf9, 0x00, 0x00, 0x00,
}
